# Main config file for training a model

# Run specifications
runname: training_dev
device: cpu # or cuda for gpu

# Paths
data_dir: "/Users/wafaa.wardah/tubCloud/nisqa_things/mini_nisqa_corpus" # main input dir with dataset samples and csv files
output_dir: "/Users/wafaa.wardah/tubCloud/experiment_outputs" # output dir, a new subfolder for current run will be created with yaml, results csv, and stored mode

# Dataset specifications
csv_file: NISQA_corpus_file.csv # csv-file with MOS (dimensions) labels and filepaths of all datasets, must be placed in 'data_dir', must contain columns 'mos', 'noi', 'dis', 'col', 'loud' with overall and dimension quality ratings
csv_deg: filepath_deg # csv column name of filepath to degraded speech sample, path must be relative to 'data_dir'
csv_db_train: # dataset names of training sets, the dataset names must be in 'db' column of csv file
    - NISQA_TRAIN_SIM
    - NISQA_TRAIN_LIVE
csv_db_val:  # dataset names of validation sets, the dataset names must be in 'db' column of csv file
    - NISQA_VAL_SIM
    - NISQA_VAL_LIVE

# Feature Extractor specifications
num_layers: 7
sample_rate: 16000  # (for max 20 second long audio)
max_length: 320000  # should be bigger than the size of the input waveform [1, 432001], designed for max 20 second long audio sampled at 16kHz. Longer waveforms will be sliced to max_length.

# Training specifications
batch_size: 3
max_epochs: 2